In [1]:
from sudoku import Sudoku

In [2]:
puzzle = Sudoku(3).difficulty(0.5)
puzzle.show()

+-------+-------+-------+
| 7 5   |   6 3 | 4   2 |
| 1   6 | 2 7   |       |
| 2   4 |   5   |   7   |
+-------+-------+-------+
|       |   8   | 3 6   |
| 6     | 3   9 |   1   |
| 8 9 3 | 6 1 5 | 2   7 |
+-------+-------+-------+
| 3     |   2   |   9 4 |
| 9   2 | 8     |   5   |
| 5   8 | 4 9   |       |
+-------+-------+-------+



In [3]:
puzzle2 = Sudoku(3).difficulty(0.8)
puzzle2.show()

+-------+-------+-------+
| 7 5   |   6   | 4     |
|       |       |       |
| 2   4 |       |   7   |
+-------+-------+-------+
|       |   8   |       |
|       | 3   9 |   1   |
|       |       | 2     |
+-------+-------+-------+
|       |       |   9 4 |
|     2 |       |   5   |
| 5     |       |       |
+-------+-------+-------+



In [4]:
solution = puzzle2.solve()
solution.show()

+-------+-------+-------+
| 7 5 8 | 1 6 3 | 4 2 9 |
| 6 1 9 | 2 4 7 | 5 3 8 |
| 2 3 4 | 9 5 8 | 1 7 6 |
+-------+-------+-------+
| 1 2 7 | 6 8 5 | 9 4 3 |
| 4 8 5 | 3 2 9 | 6 1 7 |
| 3 9 6 | 7 1 4 | 2 8 5 |
+-------+-------+-------+
| 8 6 1 | 5 3 2 | 7 9 4 |
| 9 4 2 | 8 7 6 | 3 5 1 |
| 5 7 3 | 4 9 1 | 8 6 2 |
+-------+-------+-------+



In [5]:
solution.board

[[7, 5, 8, 1, 6, 3, 4, 2, 9],
 [6, 1, 9, 2, 4, 7, 5, 3, 8],
 [2, 3, 4, 9, 5, 8, 1, 7, 6],
 [1, 2, 7, 6, 8, 5, 9, 4, 3],
 [4, 8, 5, 3, 2, 9, 6, 1, 7],
 [3, 9, 6, 7, 1, 4, 2, 8, 5],
 [8, 6, 1, 5, 3, 2, 7, 9, 4],
 [9, 4, 2, 8, 7, 6, 3, 5, 1],
 [5, 7, 3, 4, 9, 1, 8, 6, 2]]

In [6]:
puzzle2.board

[[7, 5, None, None, 6, None, 4, None, None],
 [None, None, None, None, None, None, None, None, None],
 [2, None, 4, None, None, None, None, 7, None],
 [None, None, None, None, 8, None, None, None, None],
 [None, None, None, 3, None, 9, None, 1, None],
 [None, None, None, None, None, None, 2, None, None],
 [None, None, None, None, None, None, None, 9, 4],
 [None, None, 2, None, None, None, None, 5, None],
 [5, None, None, None, None, None, None, None, None]]

In [8]:
puzzle3.solve().show()

NameError: name 'puzzle3' is not defined

In [16]:
import jax
import jax.numpy as jnp

jnp.eye(9)

DeviceArray([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 1., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 1., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 1., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 1., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 1., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 1., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 1., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [21]:
puzzle.width

3

In [12]:
from copy import deepcopy
from flax import struct
import jax.numpy as jnp


class Sudoku:
    
    def __init__(self, puzzle):
        self.width = puzzle.width
        self.size = self.width ** 2
        self.zeros = [0] * self.size
        self.map = self._make_map(self.size)
        self.puzzle = puzzle
        self.solution = puzzle.solve()
        self.solution_tensor = self.to_tensor()
        self.mask = self.make_mask()
        
    def _make_map(self, size):
        kvs = {}
        for i in range(size):
            l = deepcopy(self.zeros)
            l[i] = 1
            kvs[i+1] = l
        return kvs

    def make_mask(self):
        board = []
        for row in self.puzzle.board:
            for value in row:
                if value is not None:
                    board.append([0])
                else:
                    board.append([1])
        return jnp.array(board)
                
    def to_tensor(self):
        board = []
        for row in self.solution.board:
            for value in row:
                board.append(self.map[value])
        return jnp.array(board)
    
    @classmethod
    def from_jax(cls, flat_board):
        pass






In [13]:
sud = Sudoku(puzzle2)

In [16]:
p2 = sud.to_tensor()

In [20]:
p2.reshape((9,9,9))

DeviceArray([[[0, 0, 0, 0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 1, 0],
              [1, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1]],

             [[0, 0, 0, 0, 0, 1, 0, 0, 0],
              [1, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1],
              [0, 1, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 1, 0]],

             [[0, 1, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1],
              [0, 0, 0, 0, 1, 0, 0, 0, 0],
       

In [23]:
sud.make_mask()[..., None]

DeviceArray([[0],
             [0],
             [1],
             [1],
             [0],
             [1],
             [0],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [0],
             [1],
             [0],
             [1],
             [1],
             [1],
             [1],
             [0],
             [1],
             [1],
             [1],
             [1],
             [1],
             [0],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [0],
             [1],
             [0],
             [1],
             [0],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [1],
             [0],
             [1],
             [1],
             [1],
          