In [1]:
import numpy as np
import jax
import jax.numpy as jnp

key = jax.random.PRNGKey(12345)


/Users/dashiell/miniconda3/envs/ssm/lib/python3.9/site-packages/jax/_src/lib/__init__.py:34: UserWarning: JAX on Mac ARM machines is experimental and minimally tested. Please see https://github.com/google/jax/issues/5501 in the event of problems.
  warnings.warn("JAX on Mac ARM machines is experimental and minimally tested. "


In [2]:
key, subkey = jax.random.split(key)
rand_x = jax.random.dirichlet(subkey, jnp.ones(8192)) * 8192

In [3]:
rand_x

DeviceArray([0.05504057, 0.6655421 , 0.5469234 , ..., 0.6863714 ,
             0.09639082, 2.7146723 ], dtype=float32)

In [5]:
jnp.sort(rand_x)

DeviceArray([2.1468803e-05, 1.5872649e-04, 3.1376994e-04, ...,
             7.7768397e+00, 7.8746023e+00, 8.2197037e+00], dtype=float32)

In [68]:
key, *subkeys = jax.random.split(key, 9)


def make_array(rng):
    rand_x = jax.random.dirichlet(rng, jnp.ones(8191), shape=(120,))* 3
    x = jnp.concatenate([jnp.full((120, 1), 15.), rand_x], axis=1)
    return x[None]


batch = jnp.concatenate([make_array(k) for k in subkeys])

In [77]:
batch_mean0 = batch - jnp.mean(batch, axis=-1)[..., None]
batch_normalized = batch_mean0 / jnp.var(batch_mean0, axis=-1)[..., None]

In [54]:
x_mean0 = x - jnp.mean(x)
x_normal = x_mean0 / jnp.var(x_mean0)

In [55]:
x_normal

DeviceArray([ 5.4614417e+02, -7.2135024e-02, -7.5568900e-02, ...,
             -7.1706735e-02, -7.9752386e-02, -7.1247280e-02],            dtype=float32)

In [85]:
(batch[0, 0, :] / jnp.var(batch[0, 0, :])).sum()


DeviceArray(655.46893, dtype=float32)